<a href="https://colab.research.google.com/github/lineside0418/DeepLearning/blob/main/2048_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Main system of 2048

In [18]:
import numpy as np
import random
import matplotlib.pyplot as plt
from PIL import Image
from mpl_toolkits.axes_grid1 import ImageGrid
from google.colab import files
import sys


def initialize(size):
  banmen = np.full((size,size),0)
  return banmen
def up_remove_zeros(temp_banmen,size):
  for loop in range(size - 1):
    for y in range(0,size):
      for x in range(0,size):
        if y >= 1 and temp_banmen[y,x] != 0 and temp_banmen[y -1,x] == 0 :
          temp_banmen[y - 1,x] = temp_banmen[y,x]
          temp_banmen[y,x] = 0
  ret = temp_banmen
  return ret
def up_merge(temp_banmen,size):
  for y in range(0,size):
    for x in range(0,size):
      if y <= size - 2 and temp_banmen[y,x] != 0 and temp_banmen[y,x] == temp_banmen[y + 1,x]:
        temp_banmen[y,x] *= 2
        temp_banmen[y + 1,x] = 0
  ret = temp_banmen
  return ret
def down_remove_zeros(temp_banmen,size):
  for loop in range(size - 1):
    for y in range(size - 1,-1,-1):
      for x in range(size - 1,-1,-1):
        if y <= size - 2 and temp_banmen[y,x] != 0 and temp_banmen[y +1,x] == 0 :
          temp_banmen[y + 1,x] = temp_banmen[y,x]
          temp_banmen[y,x] = 0
  ret = temp_banmen
  return ret
def down_merge(temp_banmen,size):
  for y in range(size - 1,-1,-1):
    for x in range(size - 1,-1,-1):
      if y >= 1 and temp_banmen[y,x] != 0 and temp_banmen[y,x] == temp_banmen[y - 1,x]:
        temp_banmen[y,x] *= 2
        temp_banmen[y - 1,x] = 0
  ret = temp_banmen
  return ret
def right_remove_zeros(temp_banmen,size):
  for loop in range(size - 1):
    for x in range (size - 1,-1,-1):
      for y in range(0,size):
        if x <= size - 2 and temp_banmen[y,x] != 0 and temp_banmen[y,x + 1] == 0 :
          temp_banmen[y,x + 1] = temp_banmen[y,x]
          temp_banmen[y,x] = 0
  ret = temp_banmen
  return ret
def right_merge(temp_banmen,size):
  for x in range(size - 1,-1,-1):
    for y in range(0,size):
      if x >= 1 and temp_banmen[y,x] != 0 and temp_banmen[y,x] == temp_banmen[y,x - 1]:
        temp_banmen[y,x] *= 2
        temp_banmen[y,x - 1] = 0
  ret = temp_banmen
  return ret
def left_remove_zeros(temp_banmen,size):
  for loop in range(size - 1):
    for x in range(0,size):
      for y in range(size - 1,-1,-1):
        if x >= 1 and temp_banmen[y,x] != 0 and temp_banmen[y,x -1] == 0 :
          temp_banmen[y,x - 1] = temp_banmen[y,x]
          temp_banmen[y,x] = 0
  ret = temp_banmen
  return ret
def left_merge(temp_banmen,size):
  for x in range(0,size):
    for y in range(size - 1,-1,-1):
      if x <= size - 2 and temp_banmen[y,x] != 0 and temp_banmen[y,x] == temp_banmen[y,x + 1]:
        temp_banmen[y,x] *= 2
        temp_banmen[y,x + 1] = 0
  ret = temp_banmen
  return ret
def move_direction_select():
  move_direction = input()
  if move_direction == "w" or move_direction == "a" or move_direction == "s" or move_direction == "d" or move_direction == "up" or move_direction == "left" or move_direction == "down" or move_direction == "right":
    move_direction = move_direction
  else:
    print("w,a,s,d,up,left,down,rightの中から入力してください")
    move_direction_select
  return move_direction
def move_direction_random():
  move_direction_dic = ["w","a","s","d"]
  move_direction = random.choice(move_direction_dic)
  return move_direction
def banmen_control(banmen, move_direction, size):
    temp_banmen = banmen.copy()
    if move_direction == "w" or move_direction == "up":
        temp_banmen = up_remove_zeros(temp_banmen, size)
        temp_banmen = up_merge(temp_banmen, size)
        temp_banmen = up_remove_zeros(temp_banmen, size)
    elif move_direction == "a" or move_direction == "left":
        temp_banmen = left_remove_zeros(temp_banmen, size)
        temp_banmen = left_merge(temp_banmen, size)
        temp_banmen = left_remove_zeros(temp_banmen, size)
    elif move_direction == "s" or move_direction == "down":
        temp_banmen = down_remove_zeros(temp_banmen, size)
        temp_banmen = down_merge(temp_banmen, size)
        temp_banmen = down_remove_zeros(temp_banmen, size)
    elif move_direction == "d" or move_direction == "right":
        temp_banmen = right_remove_zeros(temp_banmen, size)
        temp_banmen = right_merge(temp_banmen, size)
        temp_banmen = right_remove_zeros(temp_banmen, size)
    return temp_banmen  # 直接 temp_banmen を返す
def get_tile_image(image_dict,value):
    file_name = image_dict.get(value, "0.png")  # 画像がない場合は 0.png
    return np.array(Image.open(file_name).resize((100, 100)))  # 100x100にリサイズ
def banmen_print(banmen,size):
  image_dict = {num: f"{num}.png" for num in [0, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]}
  fig, axes = plt.subplots(size, size, figsize=(3, 3))
  for i in range(size):
    for j in range(size):
        img = get_tile_image(image_dict,banmen[i, j])  # 盤面の数値に対応する画像を取得
        axes[i, j].imshow(img)
        axes[i, j].axis("off")  # 軸を非表示
  plt.tight_layout()
  plt.subplots_adjust(left=0, right=1, top=1, bottom=0, wspace=0.05, hspace=0.05)
  plt.show()
def game_over(banmen,size):
  can_continue = 0
  for x in range(size):
    for y in range(size):
      if x == 0 and y == 0:
        if banmen[y,x] == banmen[y + 1,x] or banmen[y,x] == banmen[y,x + 1]:
          can_continue += 1
      elif x == 0 and y == size - 1:
        if banmen[y,x] == banmen[y - 1,x] or banmen[y,x] == banmen[y,x + 1]:
          can_continue += 1
      elif x == size - 1 and y == 0:
        if banmen[y,x] == banmen[y + 1,x] or banmen[y,x] == banmen[y,x - 1]:
          can_continue += 1
      elif x == size - 1 and y == size - 1:
        if banmen[y,x] == banmen[y - 1,x] or banmen[y,x] == banmen[y,x - 1]:
          can_continue += 1
      elif x == 0 and y != 0 and y != size - 1:
        if banmen[y,x] == banmen[y + 1,x] or banmen[y,x] == banmen[y,x + 1] or banmen[y,x] == banmen[y - 1,x]:
          can_continue += 1
      elif x == size - 1 and y != 0 and y != size - 1:
        if banmen[y,x] == banmen[y - 1,x] or banmen[y,x] == banmen[y,x - 1] or banmen[y,x] == banmen[y + 1,x]:
          can_continue += 1
      elif y == 0 and x != 0 and x != size - 1:
        if banmen[y,x] == banmen[y + 1,x] or banmen[y,x] == banmen[y,x + 1] or banmen[y,x] == banmen[y,x - 1]:
          can_continue += 1
      elif y == size - 1 and x != 0 and x != size - 1:
        if banmen[y,x] == banmen[y - 1,x] or banmen[y,x] == banmen[y,x + 1] or banmen[y,x] == banmen[y,x - 1]:
          can_continue += 1
      else:
        if banmen[y,x] == banmen[y + 1,x] or banmen[y,x] == banmen[y,x + 1] or banmen[y,x] == banmen[y - 1,x] or banmen[y,x] == banmen[y + 1,x]:
          can_continue += 1
  return can_continue
def generate_num(banmen):
    generation_num = [2] * 9 + [4]  # 90% 2, 10% 4
    if np.count_nonzero(banmen == 0) == 0:
        return banmen  # 変更: そのまま返す

    candidate_y, candidate_x = np.where(banmen == 0)
    select_num = random.randint(0, len(candidate_y) - 1)  # 修正
    banmen[candidate_y[select_num], candidate_x[select_num]] = random.choice(generation_num)
    return banmen  # 修正: banmen を返す

def evaluate_board(banmen):
    """ 盤面の評価関数（スコアが高いほど良い） """
    empty_cells = np.count_nonzero(banmen == 0)  # 空きマスの数
    max_tile = np.max(banmen)  # 最大タイル
    smoothness = -np.sum(np.abs(banmen[:, :-1] - banmen[:, 1:]))  # 横のなめらかさ
    monotonicity = np.sum(banmen[1:, :] - banmen[:-1, :])  # 上下の単調性（単調な方がいい）
    return empty_cells * 100 + max_tile + smoothness + monotonicity
def minimax(banmen, depth, alpha, beta, maximizing_player, size):
    """ Minimax + αβ枝刈り """
    if depth == 0:
        return evaluate_board(banmen), None
    directions = ["w", "a", "s", "d"]
    best_move = None
    if maximizing_player:
        max_eval = -float("inf")
        for dir in directions:
            temp_banmen = banmen.copy()
            predicted = banmen_control(temp_banmen, dir, size)
            if np.array_equal(predicted, banmen):  # 動かせないならスキップ
                continue
            eval_score, _ = minimax(predicted, depth - 1, alpha, beta, False, size)
            if eval_score > max_eval:
                max_eval = eval_score
                best_move = dir
            alpha = max(alpha, eval_score)
            if beta <= alpha:  # βカット（不要な探索をスキップ）
                break
        return max_eval, best_move
    else:  # ランダムにタイルが増えるターン（最小化）
        min_eval = float("inf")
        empty_cells = np.argwhere(banmen == 0)
        if len(empty_cells) == 0:
            return evaluate_board(banmen), None  # ゲーム終了
        for cell in empty_cells:
            temp_banmen = banmen.copy()
            temp_banmen[cell[0], cell[1]] = 2  # 2が出るケースを仮定
            eval_score, _ = minimax(temp_banmen, depth - 1, alpha, beta, True, size)
            min_eval = min(min_eval, eval_score)
            beta = min(beta, eval_score)
            if beta <= alpha:  # αカット
                break
        return min_eval, None
def banmen_prediction(banmen, size):
    """ 5手先まで読む最適な手を決定 """
    _, best_direction = minimax(banmen, 6, -float("inf"), float("inf"), True, size)

    return best_direction if best_direction else "finish"

def play_2048(turn):
  sys.setrecursionlimit(8000)  # 再帰の深さの制限を2000に設定
  # size = input("盤面のサイズを入力してください")
  size = 4
  size = int(size)
  banmen = initialize(size)
  main_system(banmen,size,turn)
def turn_count():
  turn = 0
  return turn
def main_system(banmen,size,turn):
  banmen = generate_num(banmen)
  print(banmen)
  # banmen_print(banmen,size)
  learning_data.append(banmen)
  # move_direction = move_direction_select()
  # move_direction = move_direction_random()
  move_direction = banmen_prediction(banmen,size)
  learning_data_label.append(move_direction)
  turn += 1
  if move_direction != "finish":
    banmen = banmen_control(banmen,move_direction,size)
  if np.count_nonzero(banmen == 2048) >= 1:
    # banmen_print(banmen,size)
    print(banmen)
    print(str(turn)+"ターンで終了")
    print("Game Clear !!!!!!")
    print(learning_data,learning_data_label)
    return
  if np.count_nonzero(banmen == 0) == 0:
    if game_over(banmen,size) == 0:
      # banmen_print(banmen,size)
      print(banmen)
      print("\n\n＿人人人人人人人人人人人人＿\n＞　ゲームオーバーωωω　＜\n￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣\n\n")
      print(learning_data,learning_data_label)
      return
    else:
      main_system(banmen,size,turn)
  else:
    main_system(banmen,size,turn)

In [19]:
learning_data = []
learning_data_label = []

turn = turn_count()
play_2048(turn)

ストリーミング出力は最後の 5000 行に切り捨てられました。
 [  2  16   4   4]
 [512 256 128  64]]
[[  0   0   0   2]
 [  0   0  16   2]
 [  2   2  16   8]
 [512 256 128  64]]
[[  0   0   0   0]
 [  0   2   0   4]
 [  2   2  32   8]
 [512 256 128  64]]
[[  2   0   0   0]
 [  0   0   2   4]
 [  0   4  32   8]
 [512 256 128  64]]
[[  2   0   0   0]
 [  0   0   2   4]
 [  2   4  32   8]
 [512 256 128  64]]
[[  2   4   0   0]
 [  2   4   0   0]
 [  2   4  32   8]
 [512 256 128  64]]
[[  0   0   2   4]
 [  2   0   2   4]
 [  2   4  32   8]
 [512 256 128  64]]
[[  0   0   4   0]
 [  0   0   4   8]
 [  4   4  32   8]
 [512 256 128  64]]
[[  0   0   2   4]
 [  0   0   4   8]
 [  0   8  32   8]
 [512 256 128  64]]
[[  2   0   2   0]
 [  0   0   4   4]
 [  0   8  32  16]
 [512 256 128  64]]
[[  4   0   0   0]
 [  8   0   0   0]
 [  8  32  16   2]
 [512 256 128  64]]
[[  0   0   2   0]
 [  4   0   0   0]
 [ 16  32  16   2]
 [512 256 128  64]]
[[  2   0   0   0]
 [  4   2   0   0]
 [ 16  32  16   2]
 [512 256 128  64]]
[[  0

In [20]:
num_learning_data = len(learning_data)
print(len(learning_data))
print(len(learning_data_label))


for i in range (num_learning_data):
  learning_data_temp = learning_data[i]
  learning_data_label_temp = learning_data_label[i]
  for count in range(3):
    learning_data_temp = np.flipud(learning_data_temp)
    learning_data_temp = np.transpose(learning_data_temp)
    learning_data.append(learning_data_temp)
    if learning_data_label_temp == 'w':
      learning_data_label_temp = 'd'
      learning_data_label.append(learning_data_label_temp)
    elif learning_data_label_temp == 'd':
      learning_data_label_temp = 's'
      learning_data_label.append(learning_data_label_temp)
    elif learning_data_label_temp == 's':
      learning_data_label_temp = 'a'
      learning_data_label.append(learning_data_label_temp)
    elif learning_data_label_temp == 'a':
      learning_data_label_temp = 'w'
      learning_data_label.append(learning_data_label_temp)

print("convert finished")
print(len(learning_data))
print(len(learning_data_label))

977
977
convert finished
3908
3908
